/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.view;

import com.sun.glass.events.KeyEvent;
import id.co.indocyber.model.AnalisaKredit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormKredit extends javax.swing.JFrame {

    private AnalisaKredit analis;

    /**
     * Creates new form FormKredit
     */
    public FormKredit() {
        
        initComponents();
        JOptionPane.showMessageDialog(rootPane, "Selamat Sukses Login");
        btnAnalisa.setEnabled(false);
        txtLimir.setEditable(false);
        txtCicilan.setEditable(false);
        setNilaiUang();
        txtHasilAlamat.setEditable(false);
        setLocationRelativeTo(this);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        analisaKredit = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtuangMuka = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBunga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbLamaKredit = new javax.swing.JComboBox<>();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        hasilAnalisa = new javax.swing.JPanel();
        Yana = new javax.swing.JLabel();
        Yana1 = new javax.swing.JLabel();
        Yana2 = new javax.swing.JLabel();
        txtHasilNama = new javax.swing.JTextField();
        txtHasilAlamat = new java.awt.TextArea();
        txtHasilStatus = new javax.swing.JTextField();
        Yana4 = new javax.swing.JLabel();
        txtHasilTanggungan = new javax.swing.JTextField();
        Yana5 = new javax.swing.JLabel();
        txtHasilPekerjaan = new javax.swing.JTextField();
        Yana3 = new javax.swing.JLabel();
        txtHasilBonus = new javax.swing.JTextField();
        Yana6 = new javax.swing.JLabel();
        txtHasilGajiPokok = new javax.swing.JTextField();
        Yana7 = new javax.swing.JLabel();
        txtHasilPenghasilanTambahan = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtHasiluangMuka = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtHasilHarga = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtHasilBunga = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtHasilNamaBarang = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtHasilCicilan = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Yana8 = new javax.swing.JLabel();
        txtHasilUmur = new javax.swing.JTextField();
        txtHasilLamaKredit = new javax.swing.JTextField();
        lblHasil1 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblHasilTanggal = new javax.swing.JLabel();
        perhitungan = new javax.swing.JPanel();
        btnCicilan = new javax.swing.JButton();
        txtLimir = new javax.swing.JTextField();
        txtCicilan = new javax.swing.JTextField();
        btnAnalisa = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        dataPenghasilan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtGajiPokok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPenghasilanTambahan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dataNasabah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new java.awt.TextArea();
        jLabel4 = new javax.swing.JLabel();
        txtTanggungan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPekerjaan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rbtSingle = new javax.swing.JRadioButton();
        rbtMenikah = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kredit");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel44.setFont(new java.awt.Font("Source Sans Pro Light", 1, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("APLIKASI ANALISA KREDIT");
        jLabel44.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyer/image/tokbox.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(295, 295, 295))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        analisaKredit.setBackground(new java.awt.Color(255, 255, 255));
        analisaKredit.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "AnalisaKredit"));

        jLabel10.setText("Harga");

        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        jLabel11.setText("Uang Muka");

        txtuangMuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuangMukaActionPerformed(evt);
            }
        });
        txtuangMuka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuangMukaKeyTyped(evt);
            }
        });

        jLabel12.setText("Bunga Kredit");

        txtBunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBungaKeyTyped(evt);
            }
        });

        jLabel13.setText("%");

        jLabel14.setText("Lama Kredit");

        jLabel15.setText("Bulan");

        cmbLamaKredit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel21.setText("Nama Barang");

        jLabel24.setText("Rp.");

        jLabel25.setText("Rp.");

        javax.swing.GroupLayout analisaKreditLayout = new javax.swing.GroupLayout(analisaKredit);
        analisaKredit.setLayout(analisaKreditLayout);
        analisaKreditLayout.setHorizontalGroup(
            analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analisaKreditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(analisaKreditLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(analisaKreditLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(analisaKreditLayout.createSequentialGroup()
                                .addComponent(txtBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(txtuangMuka, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(analisaKreditLayout.createSequentialGroup()
                                .addComponent(cmbLamaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        analisaKreditLayout.setVerticalGroup(
            analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analisaKreditLayout.createSequentialGroup()
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtuangMuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(analisaKreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(cmbLamaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        hasilAnalisa.setBackground(new java.awt.Color(255, 255, 255));
        hasilAnalisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Hasil Analisa"));

        Yana.setText("Nama");

        Yana1.setText("Alamat");

        Yana2.setText("Status");

        txtHasilNama.setEditable(false);

        txtHasilStatus.setEditable(false);

        Yana4.setText("Jumlah Tanggungan");

        txtHasilTanggungan.setEditable(false);

        Yana5.setText("Pekerjaan");

        txtHasilPekerjaan.setEditable(false);

        Yana3.setText("Bonus");

        txtHasilBonus.setEditable(false);

        Yana6.setText("Gaji Pokok");

        txtHasilGajiPokok.setEditable(false);

        Yana7.setText("PenghasilanTambahan");

        txtHasilPenghasilanTambahan.setEditable(false);

        jLabel31.setText("Bulan");

        txtHasiluangMuka.setEditable(false);
        txtHasiluangMuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasiluangMukaActionPerformed(evt);
            }
        });

        jLabel28.setText("Uang Muka");

        jLabel34.setText("Rp.");

        jLabel29.setText("Bunga Kredit");

        jLabel32.setText("%");

        txtHasilHarga.setEditable(false);

        jLabel30.setText("Lama Kredit");

        jLabel33.setText("Rp.");

        jLabel26.setText("Nama Barang");

        txtHasilBunga.setEditable(false);

        jLabel27.setText("Harga");

        txtHasilNamaBarang.setEditable(false);

        jLabel35.setText("Rp.");

        jLabel36.setText("Rp.");

        jLabel37.setText("Rp.");

        jLabel38.setText("Orang");

        lblHasil.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(255, 0, 51));
        lblHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHasil.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Rp.");

        txtHasilCicilan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Cicilan");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("per bulan");

        Yana8.setText("Umur");

        txtHasilUmur.setEditable(false);

        txtHasilLamaKredit.setEditable(false);

        lblHasil1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblHasil1.setForeground(new java.awt.Color(51, 255, 0));
        lblHasil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHasil1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel46.setText("Tanggal");

        javax.swing.GroupLayout hasilAnalisaLayout = new javax.swing.GroupLayout(hasilAnalisa);
        hasilAnalisa.setLayout(hasilAnalisaLayout);
        hasilAnalisaLayout.setHorizontalGroup(
            hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Yana2)
                                    .addComponent(Yana1)
                                    .addComponent(Yana)
                                    .addComponent(Yana4)
                                    .addComponent(Yana5)
                                    .addComponent(Yana8))
                                .addGap(10, 10, 10)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHasilPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHasilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                        .addComponent(txtHasilTanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel38))
                                    .addComponent(txtHasilUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHasilAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHasilNama, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Yana7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Yana3)
                                                .addComponent(Yana6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                                    .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel36)
                                                        .addComponent(jLabel37)
                                                        .addComponent(jLabel33))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtHasilNamaBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtHasilBonus, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtHasilPenghasilanTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtHasiluangMuka)))
                                                .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                                    .addComponent(jLabel35)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtHasilGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilAnalisaLayout.createSequentialGroup()
                                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtHasilLamaKredit)
                                                    .addComponent(txtHasilBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel32))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilAnalisaLayout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(jLabel31)))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilAnalisaLayout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHasilHarga))))
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addComponent(lblHasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel39)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtHasilCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHasilTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)))
                                .addComponent(jLabel41)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        hasilAnalisaLayout.setVerticalGroup(
            hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yana)
                    .addComponent(txtHasilNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yana6)
                    .addComponent(txtHasilGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Yana7)
                            .addComponent(txtHasilPenghasilanTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Yana3)
                            .addComponent(txtHasilBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHasilNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(txtHasilHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Yana1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHasiluangMuka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHasilBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(txtHasilLamaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30)))
                            .addGroup(hasilAnalisaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHasilAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Yana8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHasilUmur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Yana2)
                                    .addComponent(txtHasilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Yana4)
                                    .addComponent(txtHasilTanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Yana5)
                                    .addComponent(txtHasilPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilAnalisaLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilAnalisaLayout.createSequentialGroup()
                        .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHasilTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasilCicilan)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hasilAnalisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        perhitungan.setBackground(new java.awt.Color(255, 255, 255));
        perhitungan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Perhitungan"));

        btnCicilan.setText("Hitung");
        btnCicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCicilanActionPerformed(evt);
            }
        });

        btnAnalisa.setText("Analisa");
        btnAnalisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisaActionPerformed(evt);
            }
        });

        jLabel22.setText("Rp.");

        jLabel23.setText("Rp.");

        jLabel42.setText("Limit");

        jLabel43.setText("Cicilan");

        javax.swing.GroupLayout perhitunganLayout = new javax.swing.GroupLayout(perhitungan);
        perhitungan.setLayout(perhitunganLayout);
        perhitunganLayout.setHorizontalGroup(
            perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perhitunganLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLimir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        perhitunganLayout.setVerticalGroup(
            perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perhitunganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel42))
                    .addComponent(btnCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel43)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataPenghasilan.setBackground(new java.awt.Color(255, 255, 255));
        dataPenghasilan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Penghasilan"));

        jLabel7.setText("Gaji Pokok");

        txtGajiPokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGajiPokokKeyTyped(evt);
            }
        });

        jLabel8.setText("Penghasilan Tambahan");

        txtPenghasilanTambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenghasilanTambahanActionPerformed(evt);
            }
        });
        txtPenghasilanTambahan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPenghasilanTambahanKeyTyped(evt);
            }
        });

        jLabel9.setText("Bonus");

        txtBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBonusKeyTyped(evt);
            }
        });

        jLabel18.setText("Rp.");

        jLabel19.setText("Rp.");

        jLabel20.setText("Rp.");

        javax.swing.GroupLayout dataPenghasilanLayout = new javax.swing.GroupLayout(dataPenghasilan);
        dataPenghasilan.setLayout(dataPenghasilanLayout);
        dataPenghasilanLayout.setHorizontalGroup(
            dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenghasilanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPenghasilanTambahan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBonus))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dataPenghasilanLayout.setVerticalGroup(
            dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenghasilanLayout.createSequentialGroup()
                .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPenghasilanTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPenghasilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        dataNasabah.setBackground(new java.awt.Color(255, 255, 255));
        dataNasabah.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Nasabah"));
        dataNasabah.setPreferredSize(new java.awt.Dimension(276, 294));

        jLabel1.setText("Nama");

        jLabel2.setText("Umur");

        txtUmur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUmurKeyTyped(evt);
            }
        });

        jLabel3.setText("Alamat");

        jLabel4.setText("Status");

        txtTanggungan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTanggunganKeyTyped(evt);
            }
        });

        jLabel5.setText("Jumlah Tanggungan");

        jLabel6.setText("Pekerjaan");

        jLabel16.setText("th");

        jLabel17.setText("Orang");

        rbtSingle.setText("Single");

        rbtMenikah.setText("Menikah");

        javax.swing.GroupLayout dataNasabahLayout = new javax.swing.GroupLayout(dataNasabah);
        dataNasabah.setLayout(dataNasabahLayout);
        dataNasabahLayout.setHorizontalGroup(
            dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataNasabahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataNasabahLayout.createSequentialGroup()
                        .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(dataNasabahLayout.createSequentialGroup()
                        .addComponent(txtTanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(dataNasabahLayout.createSequentialGroup()
                        .addComponent(rbtSingle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtMenikah))
                    .addComponent(txtPekerjaan)
                    .addComponent(txtNama)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        dataNasabahLayout.setVerticalGroup(
            dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataNasabahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtSingle)
                    .addComponent(rbtMenikah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTanggungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(perhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(dataNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(analisaKredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dataPenghasilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(hasilAnalisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hasilAnalisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(dataPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(analisaKredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dataNasabah, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(perhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(419, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuangMukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuangMukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangMukaActionPerformed

    private void txtHasiluangMukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasiluangMukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasiluangMukaActionPerformed

    private void btnCicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCicilanActionPerformed
        String inputPokokPinjaman = txtHarga.getText();
        int pokokPinjaman = Integer.parseInt(inputPokokPinjaman);
        String inputBonus = txtBonus.getText();
        int bonus = Integer.parseInt(inputBonus);
        String inputBunga = txtBunga.getText();
        int bunga = Integer.parseInt(inputBunga);
        String inputPenghasilanTambahan = txtPenghasilanTambahan.getText();
        int penghasilanTambahan = Integer.parseInt(inputPenghasilanTambahan);
        String inputGajiPokok = txtGajiPokok.getText();
        int gajiPokok = Integer.parseInt(inputGajiPokok);
        String inputUangMuka = txtuangMuka.getText();
        int uangMuka = Integer.parseInt(inputUangMuka);
        String inputBulan = (String) cmbLamaKredit.getSelectedItem();
        int bulan = Integer.parseInt(inputBulan);
        String inputTanggungan = txtTanggungan.getText();
        int tanggungan = Integer.parseInt(inputTanggungan);

        AnalisaKredit analis = new AnalisaKredit(pokokPinjaman, uangMuka, bunga, bulan, tanggungan, gajiPokok, bonus, penghasilanTambahan);
        double hasilCicilan = analis.cicilanPerbulan();
        String lemparHasilCicilsn = String.format("%,.2f", hasilCicilan);
        txtCicilan.setText(lemparHasilCicilsn);
        double hasilLimit = analis.limitPinjaman();
        String lemparHasilLimit = String.format("%,.2f", hasilLimit);
        txtLimir.setText(lemparHasilLimit);
        btnAnalisa.setEnabled(true);
        lblHasil.setText(null);
        lblHasil1.setText(null);
    }//GEN-LAST:event_btnCicilanActionPerformed

    private void btnAnalisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisaActionPerformed
        try {
            String inputPokokPinjaman = txtHarga.getText();
            int pokokPinjaman = Integer.parseInt(inputPokokPinjaman);
            String inputBonus = txtBonus.getText();
            int bonus = Integer.parseInt(inputBonus);
            String inputBunga = txtBunga.getText();
            int bunga = Integer.parseInt(inputBunga);
            String inputPenghasilanTambahan = txtPenghasilanTambahan.getText();
            int penghasilanTambahan = Integer.parseInt(inputPenghasilanTambahan);
            String inputGajiPokok = txtGajiPokok.getText();
            int gajiPokok = Integer.parseInt(inputGajiPokok);
            String inputUangMuka = txtuangMuka.getText();
            int uangMuka = Integer.parseInt(inputUangMuka);
            String inputBulan = (String) cmbLamaKredit.getSelectedItem();
            int bulan = Integer.parseInt(inputBulan);
            String inputTanggungan = txtTanggungan.getText();
            int tanggungan = Integer.parseInt(inputTanggungan);

            AnalisaKredit analis = new AnalisaKredit(pokokPinjaman, uangMuka, bunga, bulan, tanggungan, gajiPokok, bonus, penghasilanTambahan);
            double cicilan = analis.cicilanPerbulan();
            double limit = analis.limitPinjaman();
            boolean correct = analis.isIsApprove(limit, cicilan);
            if (correct) {
                lblHasil1.setText("Disetujui");
                String hasilCicilan = txtCicilan.getText();
                txtHasilCicilan.setText(hasilCicilan);
                Date dNow = new Date();
                SimpleDateFormat ft = 
                new SimpleDateFormat ("EEEE dd-MMMM-yyyy 'at' hh:mm:ss a ");
                lblHasilTanggal.setText(ft.format(dNow));
            } else {
                lblHasil.setText("Ditolak");
            }
            setTeksInputan();
            resetForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Isi Semua Data");
        }
    }//GEN-LAST:event_btnAnalisaActionPerformed

    private void txtPenghasilanTambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenghasilanTambahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenghasilanTambahanActionPerformed

    private void txtUmurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUmurKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtUmurKeyTyped

    private void txtGajiPokokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGajiPokokKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtGajiPokokKeyTyped

    private void txtPenghasilanTambahanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPenghasilanTambahanKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtPenghasilanTambahanKeyTyped

    private void txtBonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBonusKeyTyped
       char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtBonusKeyTyped

    private void txtuangMukaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuangMukaKeyTyped
       char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtuangMukaKeyTyped

    private void txtBungaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBungaKeyTyped
       char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtBungaKeyTyped

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtHargaKeyTyped

    private void txtTanggunganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTanggunganKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACKSPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Masukkan Angka");
            evt.consume();
        }
    }//GEN-LAST:event_txtTanggunganKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKredit().setVisible(true);
            }
        });
    }

    public void getNilai() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Yana;
    private javax.swing.JLabel Yana1;
    private javax.swing.JLabel Yana2;
    private javax.swing.JLabel Yana3;
    private javax.swing.JLabel Yana4;
    private javax.swing.JLabel Yana5;
    private javax.swing.JLabel Yana6;
    private javax.swing.JLabel Yana7;
    private javax.swing.JLabel Yana8;
    private javax.swing.JPanel analisaKredit;
    private javax.swing.JButton btnAnalisa;
    private javax.swing.JButton btnCicilan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbLamaKredit;
    private javax.swing.JPanel dataNasabah;
    private javax.swing.JPanel dataPenghasilan;
    private javax.swing.JPanel hasilAnalisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblHasil1;
    private javax.swing.JLabel lblHasilTanggal;
    private javax.swing.JPanel perhitungan;
    private javax.swing.JRadioButton rbtMenikah;
    private javax.swing.JRadioButton rbtSingle;
    private java.awt.TextArea txtAlamat;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtBunga;
    private javax.swing.JTextField txtCicilan;
    private javax.swing.JTextField txtGajiPokok;
    private javax.swing.JTextField txtHarga;
    private java.awt.TextArea txtHasilAlamat;
    private javax.swing.JTextField txtHasilBonus;
    private javax.swing.JTextField txtHasilBunga;
    private javax.swing.JTextField txtHasilCicilan;
    private javax.swing.JTextField txtHasilGajiPokok;
    private javax.swing.JTextField txtHasilHarga;
    private javax.swing.JTextField txtHasilLamaKredit;
    private javax.swing.JTextField txtHasilNama;
    private javax.swing.JTextField txtHasilNamaBarang;
    private javax.swing.JTextField txtHasilPekerjaan;
    private javax.swing.JTextField txtHasilPenghasilanTambahan;
    private javax.swing.JTextField txtHasilStatus;
    private javax.swing.JTextField txtHasilTanggungan;
    private javax.swing.JTextField txtHasilUmur;
    private javax.swing.JTextField txtHasiluangMuka;
    private javax.swing.JTextField txtLimir;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtPekerjaan;
    private javax.swing.JTextField txtPenghasilanTambahan;
    private javax.swing.JTextField txtTanggungan;
    private javax.swing.JTextField txtUmur;
    private javax.swing.JTextField txtuangMuka;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        setNilaiUang();
        txtNama.setText(null);
        txtCicilan.setText(null);
        txtLimir.setText(null);
        txtNamaBarang.setText(null);
        txtPekerjaan.setText(null);
        txtUmur.setText(null);
        String inputBulan = (String) cmbLamaKredit.getSelectedItem();
        if (!(inputBulan.equalsIgnoreCase("1"))) {
            cmbLamaKredit.setSelectedItem("1");
        }
        btnAnalisa.setEnabled(false);
        txtAlamat.setText(null);

    }

    private void setNilaiUang() {
        txtTanggungan.setText("0");
        txtGajiPokok.setText("0");
        txtPenghasilanTambahan.setText("0");
        txtuangMuka.setText("0");
        txtBonus.setText("0");
        txtBunga.setText("0");
        txtHarga.setText("0");
    }

    private void setTeksInputan() {
        String nama = txtNama.getText();
        txtHasilNama.setText(nama);
        String alamat = txtAlamat.getText();
        txtHasilAlamat.setText(alamat);
        String umur = txtUmur.getText();
        txtHasilUmur.setText(umur);
        String status = "";
        if (rbtSingle.isSelected()) {
            status = rbtSingle.getText();
        } else {
            status = rbtMenikah.getText();
        }
        txtHasilStatus.setText(status);
        String jumlahTanggungan = txtTanggungan.getText();
        txtHasilTanggungan.setText(jumlahTanggungan);
        String pekerjaan = txtPekerjaan.getText();
        txtHasilPekerjaan.setText(pekerjaan);
        String gajiPokok = txtGajiPokok.getText();
        txtHasilGajiPokok.setText(gajiPokok);
        String penghasilanTambahan = txtPenghasilanTambahan.getText();
        txtHasilPenghasilanTambahan.setText(penghasilanTambahan);
        String bonus = txtBonus.getText();
        txtHasilBonus.setText(bonus);
        String namaBarang = txtNamaBarang.getText();
        txtHasilNamaBarang.setText(namaBarang);
        String harga = txtHarga.getText();
        txtHasilHarga.setText(harga);
        String uangMuka = txtuangMuka.getText();
        txtHasiluangMuka.setText(uangMuka);
        String bunga = txtBunga.getText();
        txtHasilBunga.setText(bunga);
        String inputBulan = (String) cmbLamaKredit.getSelectedItem();
        txtHasilLamaKredit.setText(inputBulan);

    }
}
